/** Auto-generated by scripts/generate_geo_nested.py — do not edit by hand. */

export interface GeoBBox {
	latMin: number;
	latMax: number;
	lonMin: number;
	lonMax: number;
	airports?: string[];
}

export interface GeoDistrict extends GeoBBox {
	code: string;
	nameZh: string;
}

export interface GeoCity extends GeoBBox {
	code: string;
	nameZh: string;
	districts?: GeoDistrict[];
}

export type NestedGeoMap = Record<string, Record<string, GeoCity[]>>;

export const NESTED_GEO_CN: NestedGeoMap = {
  "BJ": [
      { code: "BJ-URBAN", nameZh: "北京市区", latMin: 39.75, latMax: 40.05, lonMin: 116.1, lonMax: 116.65, airports: ["PEK", "PKX"], districts: [{ code: "BJ-CY", nameZh: "朝阳", latMin: 39.85, latMax: 40.05, lonMin: 116.35, lonMax: 116.65 }, { code: "BJ-HD", nameZh: "海淀", latMin: 39.9, latMax: 40.1, lonMin: 116.1, lonMax: 116.35 }, { code: "BJ-DC", nameZh: "东城西城", latMin: 39.88, latMax: 39.96, lonMin: 116.35, lonMax: 116.45 }, { code: "BJ-FT", nameZh: "丰台大兴", latMin: 39.68, latMax: 39.88, lonMin: 116.2, lonMax: 116.55 }] },
    ],
  "TJ": [
      { code: "TJ-CITY", nameZh: "天津市区", latMin: 38.9, latMax: 39.25, lonMin: 116.95, lonMax: 117.45, airports: ["TSN"] },
    ],
  "HE": [
      { code: "SJW-CITY", nameZh: "石家庄", latMin: 37.9, latMax: 38.25, lonMin: 114.3, lonMax: 114.8, airports: ["SJW"] },
    ],
  "SX": [
      { code: "TYN-CITY", nameZh: "太原", latMin: 37.6, latMax: 38.1, lonMin: 112.4, lonMax: 112.7, airports: ["TYN"] },
    ],
  "NM": [
      { code: "HET-CITY", nameZh: "呼和浩特", latMin: 40.7, latMax: 41.0, lonMin: 111.5, lonMax: 112.0, airports: ["HET"] },
    ],
  "LN": [
      { code: "SHE-CITY", nameZh: "沈阳", latMin: 41.6, latMax: 42.0, lonMin: 123.2, lonMax: 123.6, airports: ["SHE"] },
      { code: "DLC-CITY", nameZh: "大连", latMin: 38.8, latMax: 39.2, lonMin: 121.4, lonMax: 122.0, airports: ["DLC"] },
    ],
  "JL": [
      { code: "CGQ-CITY", nameZh: "长春", latMin: 43.7, latMax: 44.1, lonMin: 125.1, lonMax: 125.5, airports: ["CGQ"] },
    ],
  "HL": [
      { code: "HRB-CITY", nameZh: "哈尔滨", latMin: 45.6, latMax: 46.0, lonMin: 126.4, lonMax: 126.8, airports: ["HRB"] },
    ],
  "SH": [
      { code: "PVG-AREA", nameZh: "浦东", latMin: 30.95, latMax: 31.35, lonMin: 121.6, lonMax: 122.0, airports: ["PVG"], districts: [{ code: "SH-PD-CORE", nameZh: "浦东核心", latMin: 31.1, latMax: 31.3, lonMin: 121.7, lonMax: 121.95 }, { code: "SH-PD-SOUTH", nameZh: "浦东南部", latMin: 30.95, latMax: 31.1, lonMin: 121.6, lonMax: 121.8 }] },
      { code: "SHA-AREA", nameZh: "虹桥", latMin: 31.1, latMax: 31.25, lonMin: 121.3, lonMax: 121.45, airports: ["SHA"] },
    ],
  "JS": [
      { code: "NKG-CITY", nameZh: "南京", latMin: 31.9, latMax: 32.15, lonMin: 118.6, lonMax: 119.0, airports: ["NKG"] },
      { code: "WUX-CITY", nameZh: "无锡", latMin: 31.45, latMax: 31.65, lonMin: 120.2, lonMax: 120.45, airports: ["WUX"] },
    ],
  "ZJ": [
      { code: "HGH-CITY", nameZh: "杭州", latMin: 30.1, latMax: 30.4, lonMin: 119.9, lonMax: 120.35, airports: ["HGH"] },
      { code: "NGB-CITY", nameZh: "宁波", latMin: 29.7, latMax: 30.0, lonMin: 121.4, lonMax: 121.7, airports: ["NGB"] },
    ],
  "AH": [
      { code: "HFE-CITY", nameZh: "合肥", latMin: 31.7, latMax: 32.0, lonMin: 117.1, lonMax: 117.45, airports: ["HFE"] },
    ],
  "FJ": [
      { code: "XMN-CITY", nameZh: "厦门", latMin: 24.4, latMax: 24.65, lonMin: 118.05, lonMax: 118.25, airports: ["XMN"] },
      { code: "FOC-CITY", nameZh: "福州", latMin: 25.9, latMax: 26.15, lonMin: 119.2, lonMax: 119.45, airports: ["FOC"] },
    ],
  "JX": [
      { code: "KHN-CITY", nameZh: "南昌", latMin: 28.5, latMax: 28.75, lonMin: 115.8, lonMax: 116.0, airports: ["KHN"] },
    ],
  "SD": [
      { code: "TNA-CITY", nameZh: "济南", latMin: 36.5, latMax: 36.85, lonMin: 116.9, lonMax: 117.2, airports: ["TNA"] },
      { code: "TAO-CITY", nameZh: "青岛", latMin: 36.0, latMax: 36.3, lonMin: 120.25, lonMax: 120.5, airports: ["TAO"] },
    ],
  "HA": [
      { code: "CGO-CITY", nameZh: "郑州", latMin: 34.6, latMax: 34.9, lonMin: 113.6, lonMax: 113.9, airports: ["CGO"] },
      { code: "LYA-CITY", nameZh: "洛阳", latMin: 34.55, latMax: 34.75, lonMin: 112.35, lonMax: 112.55 },
    ],
  "HB": [
      { code: "WUH-CITY", nameZh: "武汉", latMin: 30.45, latMax: 30.75, lonMin: 114.1, lonMax: 114.5, airports: ["WUH"] },
    ],
  "HN": [
      { code: "CSX-CITY", nameZh: "长沙", latMin: 28.05, latMax: 28.35, lonMin: 112.85, lonMax: 113.15, airports: ["CSX"] },
    ],
  "GD": [
      { code: "CAN-AREA", nameZh: "广州", latMin: 22.95, latMax: 23.45, lonMin: 113.15, lonMax: 113.55, airports: ["CAN"], districts: [{ code: "GZ-TH", nameZh: "天河越秀", latMin: 23.1, latMax: 23.2, lonMin: 113.25, lonMax: 113.4 }, { code: "GZ-BY", nameZh: "白云", latMin: 23.3, latMax: 23.45, lonMin: 113.25, lonMax: 113.4 }, { code: "GZ-NS", nameZh: "南沙番禺", latMin: 22.95, latMax: 23.1, lonMin: 113.3, lonMax: 113.55 }] },
      { code: "SZX-AREA", nameZh: "深圳", latMin: 22.45, latMax: 22.75, lonMin: 113.85, lonMax: 114.25, airports: ["SZX"], districts: [{ code: "SZ-FT", nameZh: "福田罗湖", latMin: 22.5, latMax: 22.58, lonMin: 114.0, lonMax: 114.15 }, { code: "SZ-NS", nameZh: "南山", latMin: 22.48, latMax: 22.55, lonMin: 113.85, lonMax: 114.0 }, { code: "SZ-BA", nameZh: "宝安", latMin: 22.6, latMax: 22.75, lonMin: 113.85, lonMax: 114.05 }] },
      { code: "ZUH-CITY", nameZh: "珠海", latMin: 22.0, latMax: 22.4, lonMin: 113.45, lonMax: 113.65, airports: ["ZUH"] },
    ],
  "GX": [
      { code: "NNG-CITY", nameZh: "南宁", latMin: 22.7, latMax: 22.9, lonMin: 108.25, lonMax: 108.45, airports: ["NNG"] },
    ],
  "HI": [
      { code: "HAK-CITY", nameZh: "海口", latMin: 19.9, latMax: 20.1, lonMin: 110.25, lonMax: 110.45, airports: ["HAK"] },
      { code: "SYX-CITY", nameZh: "三亚", latMin: 18.2, latMax: 18.4, lonMin: 109.35, lonMax: 109.55, airports: ["SYX"] },
    ],
  "CQ": [
      { code: "CKG-CITY", nameZh: "重庆", latMin: 29.4, latMax: 29.75, lonMin: 106.4, lonMax: 106.65, airports: ["CKG"] },
    ],
  "SC": [
      { code: "CTU-AREA", nameZh: "成都", latMin: 30.45, latMax: 30.8, lonMin: 103.9, lonMax: 104.2, airports: ["CTU", "TFU"] },
    ],
  "GZ": [
      { code: "KWE-CITY", nameZh: "贵阳", latMin: 26.5, latMax: 26.65, lonMin: 106.6, lonMax: 106.8, airports: ["KWE"] },
    ],
  "YN": [
      { code: "KMG-CITY", nameZh: "昆明", latMin: 24.9, latMax: 25.1, lonMin: 102.7, lonMax: 102.95, airports: ["KMG"] },
    ],
  "XZ": [
      { code: "LXA-CITY", nameZh: "拉萨", latMin: 29.6, latMax: 29.7, lonMin: 90.95, lonMax: 91.15, airports: ["LXA"] },
    ],
  "SN": [
      { code: "XIY-CITY", nameZh: "西安", latMin: 34.3, latMax: 34.5, lonMin: 108.7, lonMax: 109.0, airports: ["XIY"] },
    ],
  "GS": [
      { code: "LHW-CITY", nameZh: "兰州", latMin: 36.0, latMax: 36.1, lonMin: 103.55, lonMax: 103.75, airports: ["LHW"] },
    ],
  "QH": [
      { code: "XNN-CITY", nameZh: "西宁", latMin: 36.5, latMax: 36.65, lonMin: 101.7, lonMax: 101.85, airports: ["XNN"] },
    ],
  "NX": [
      { code: "INC-CITY", nameZh: "银川", latMin: 38.4, latMax: 38.55, lonMin: 106.35, lonMax: 106.5, airports: ["INC"] },
    ],
  "XJ": [
      { code: "URC-CITY", nameZh: "乌鲁木齐", latMin: 43.8, latMax: 44.0, lonMin: 87.4, lonMax: 87.65, airports: ["URC"] },
    ]
};

export const NESTED_GEO_US: NestedGeoMap = {
  "CA": [
      { code: "CA-LA", nameZh: "洛杉矶", latMin: 33.7, latMax: 34.35, lonMin: -118.65, lonMax: -117.9, airports: ["LAX"] },
      { code: "CA-SF", nameZh: "旧金山湾区", latMin: 37.45, latMax: 37.85, lonMin: -122.55, lonMax: -121.9, airports: ["SFO", "SJC", "OAK"] },
      { code: "CA-SD", nameZh: "圣迭戈", latMin: 32.6, latMax: 33.1, lonMin: -117.3, lonMax: -116.9, airports: ["SAN"] },
    ],
  "NY": [
      { code: "NY-NYC", nameZh: "纽约都会", latMin: 40.55, latMax: 40.9, lonMin: -74.25, lonMax: -73.7, airports: ["JFK", "LGA", "EWR"], districts: [{ code: "NY-MAN", nameZh: "曼哈顿", latMin: 40.7, latMax: 40.82, lonMin: -74.02, lonMax: -73.9 }, { code: "NY-QUE", nameZh: "皇后区", latMin: 40.65, latMax: 40.78, lonMin: -73.95, lonMax: -73.75 }, { code: "NY-BRK", nameZh: "布鲁克林", latMin: 40.58, latMax: 40.7, lonMin: -74.05, lonMax: -73.9 }] },
    ],
  "TX": [
      { code: "TX-DFW", nameZh: "达拉斯沃斯堡", latMin: 32.6, latMax: 33.1, lonMin: -97.2, lonMax: -96.5, airports: ["DFW", "DAL"] },
      { code: "TX-HOU", nameZh: "休斯顿", latMin: 29.6, latMax: 30.05, lonMin: -95.65, lonMax: -95.1, airports: ["IAH", "HOU"] },
    ],
  "FL": [
      { code: "FL-MIA", nameZh: "迈阿密", latMin: 25.7, latMax: 26.0, lonMin: -80.35, lonMax: -80.1, airports: ["MIA", "FLL"] },
      { code: "FL-ORL", nameZh: "奥兰多", latMin: 28.35, latMax: 28.6, lonMin: -81.5, lonMax: -81.2, airports: ["MCO"] },
    ]
};

export const NESTED_GEO_JP: NestedGeoMap = {
  "JP-KNT": [
      { code: "TYO-AREA", nameZh: "东京", latMin: 35.55, latMax: 35.85, lonMin: 139.55, lonMax: 139.9, airports: ["HND", "NRT"], districts: [{ code: "TYO-C23", nameZh: "都心", latMin: 35.65, latMax: 35.72, lonMin: 139.68, lonMax: 139.78 }, { code: "TYO-C24", nameZh: "湾岸", latMin: 35.6, latMax: 35.68, lonMin: 139.75, lonMax: 139.9 }] },
    ],
  "JP-KNS": [
      { code: "OSA-CITY", nameZh: "大阪", latMin: 34.6, latMax: 34.75, lonMin: 135.4, lonMax: 135.6, airports: ["KIX", "ITM"] },
    ]
};

export const NESTED_GEO_DE: NestedGeoMap = {
  "DE-BY": [
      { code: "DE-MUC", nameZh: "慕尼黑", latMin: 48.1, latMax: 48.25, lonMin: 11.45, lonMax: 11.7, airports: ["MUC"] },
    ],
  "DE-BE": [
      { code: "DE-BER", nameZh: "柏林", latMin: 52.45, latMax: 52.58, lonMin: 13.3, lonMax: 13.55, airports: ["BER"] },
    ]
};
